import {BubbleActivity, BubbleActivityRange, CreateFermentationMeasurement, FermentationDetails, FermentationGatewaySensorStatus} from '../model/Fermentation';

export enum FermentationActionTypes {
  LOAD = 'Fermentation.LOAD', LOAD_SUCCESS = 'Fermentation.LOAD_SUCCESS', LOAD_FAILURE = 'Fermentation.LOAD_FAILURE',
  CREATE_MEASUREMENT = 'Fermentation.CREATE_MEASUREMENT', CREATE_MEASUREMENT_SUCCESS = 'Fermentation.CREATE_MEASUREMENT_SUCCESS', CREATE_MEASUREMENT_FAILURE = 'Fermentation.CREATE_MEASUREMENT_FAILURE',
  COMPLETE_ACTION = 'Fermentation.COMPLETE_ACTION', COMPLETE_ACTION_SUCCESS = 'Fermentation.COMPLETE_ACTION_SUCCESS', COMPLETE_ACTION_FAILURE = 'Fermentation.COMPLETE_ACTION_FAILURE',
  SKIP_ACTION = 'Fermentation.SKIP_ACTION', SKIP_ACTION_SUCCESS = 'Fermentation.SKIP_ACTION_SUCCESS', SKIP_ACTION_FAILURE = 'Fermentation.SKIP_ACTION_FAILURE',
  ASSIGN_DEVICE = 'Fermentation.ASSIGN_DEVICE', ASSIGN_DEVICE_SUCCESS = 'Fermentation.ASSIGN_DEVICE_SUCCESS', ASSIGN_DEVICE_FAILURE = 'Fermentation.ASSIGN_DEVICE_FAILURE',
  GATEWAY_CONNECT = 'Fermentation.GATEWAY_CONNECT', GATEWAY_DISCONNECT = 'Fermentation.GATEWAY_DISCONNECT', GATEWAY_CONNECTION_CHANGED = 'Fermentation.GATEWAY_CONNECTION_CHANGED',
  GATEWAY_SNAPSHOT_RECEIVED = 'Fermentation.GATEWAY_SNAPSHOT_RECEIVED', GATEWAY_SENSOR_STATUS_CHANGED = 'Fermentation.GATEWAY_SENSOR_STATUS_CHANGED',
  LOAD_BUBBLE_ACTIVITY = 'Fermentation.LOAD_BUBBLE_ACTIVITY', LOAD_BUBBLE_ACTIVITY_SUCCESS = 'Fermentation.LOAD_BUBBLE_ACTIVITY_SUCCESS', LOAD_BUBBLE_ACTIVITY_FAILURE = 'Fermentation.LOAD_BUBBLE_ACTIVITY_FAILURE',
}
export const FermentationActions = {
  load: (brewId: string) => ({type: FermentationActionTypes.LOAD, payload: {brewId}}),
  loadSuccess: (brewId: string, details: FermentationDetails) => ({type: FermentationActionTypes.LOAD_SUCCESS, payload: {brewId, details}}),
  loadFailure: (brewId: string, error: string) => ({type: FermentationActionTypes.LOAD_FAILURE, payload: {brewId, error}}),
  createMeasurement: (measurement: CreateFermentationMeasurement) => ({type: FermentationActionTypes.CREATE_MEASUREMENT, payload: {measurement}}),
  createMeasurementSuccess: (brewId: string) => ({type: FermentationActionTypes.CREATE_MEASUREMENT_SUCCESS, payload: {brewId}}),
  createMeasurementFailure: (brewId: string, error: string) => ({type: FermentationActionTypes.CREATE_MEASUREMENT_FAILURE, payload: {brewId, error}}),
  completeAction: (brewId: string, actionId: string) => ({type: FermentationActionTypes.COMPLETE_ACTION, payload: {brewId, actionId}}),
  completeActionSuccess: (brewId: string, actionId: string) => ({type: FermentationActionTypes.COMPLETE_ACTION_SUCCESS, payload: {brewId, actionId}}),
  completeActionFailure: (brewId: string, actionId: string, error: string) => ({type: FermentationActionTypes.COMPLETE_ACTION_FAILURE, payload: {brewId, actionId, error}}),
  skipAction: (brewId: string, actionId: string) => ({type: FermentationActionTypes.SKIP_ACTION, payload: {brewId, actionId}}),
  skipActionSuccess: (brewId: string, actionId: string) => ({type: FermentationActionTypes.SKIP_ACTION_SUCCESS, payload: {brewId, actionId}}),
  skipActionFailure: (brewId: string, actionId: string, error: string) => ({type: FermentationActionTypes.SKIP_ACTION_FAILURE, payload: {brewId, actionId, error}}),
  assignDevice: (deviceId: string, brewId: string) => ({type: FermentationActionTypes.ASSIGN_DEVICE, payload: {deviceId, brewId}}),
  assignDeviceSuccess: (deviceId: string, brewId: string) => ({type: FermentationActionTypes.ASSIGN_DEVICE_SUCCESS, payload: {deviceId, brewId}}),
  assignDeviceFailure: (deviceId: string, brewId: string, error: string) => ({type: FermentationActionTypes.ASSIGN_DEVICE_FAILURE, payload: {deviceId, brewId, error}}),
  gatewayConnect: () => ({type: FermentationActionTypes.GATEWAY_CONNECT}),
  gatewayDisconnect: () => ({type: FermentationActionTypes.GATEWAY_DISCONNECT}),
  gatewayConnectionChanged: (connected: boolean) => ({type: FermentationActionTypes.GATEWAY_CONNECTION_CHANGED, payload: {connected}}),
  gatewaySnapshotReceived: (sensors: FermentationGatewaySensorStatus[]) => ({type: FermentationActionTypes.GATEWAY_SNAPSHOT_RECEIVED, payload: {sensors}}),
  gatewaySensorStatusChanged: (sensor: FermentationGatewaySensorStatus) => ({type: FermentationActionTypes.GATEWAY_SENSOR_STATUS_CHANGED, payload: {sensor}}),
  loadBubbleActivity: (brewId: string, range: BubbleActivityRange) => ({type: FermentationActionTypes.LOAD_BUBBLE_ACTIVITY, payload: {brewId, range}}),
  loadBubbleActivitySuccess: (brewId: string, range: BubbleActivityRange, activity: BubbleActivity[]) => ({type: FermentationActionTypes.LOAD_BUBBLE_ACTIVITY_SUCCESS, payload: {brewId, range, activity}}),
  loadBubbleActivityFailure: (brewId: string, range: BubbleActivityRange, error: string) => ({type: FermentationActionTypes.LOAD_BUBBLE_ACTIVITY_FAILURE, payload: {brewId, range, error}}),
};
